title: Growing With W
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: crackinggood
github_username:  crackinggood
rss: rss

show_excerpts: false # set to true to show excerpts on the homepage

# growing-with-w-theme date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
growing-with-w-theme:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: growing-with-w-theme

plugins:
 - jekyll-feed
 - jekyll-seo-tag
